In [5]:
import numpy as np
x=np.array(15)
print("1D : ",x)
print("dimensio: ",x.ndim)   #ndim use here to find dimension of the numpy array

1D :  15
dimensio:  0


In [6]:
import numpy as np
x=np.array([0,1,2,3,4])
print("val : ",x[4])
print("array : ",x)
print("dimension: ",x.ndim)

val :  4
array :  [0 1 2 3 4]
dimension:  1


In [9]:
import numpy as np
x=np.array([[0,1,2,3,4],[5,6,7,8,10]])
print("2D : ",x)
print("1D from 2D : ",x[1])
print("element from 2D : ",x[1][2])
print("dimension: ",x.ndim)

2D :  [[ 0  1  2  3  4]
 [ 5  6  7  8 10]]
1D from 2D :  [ 5  6  7  8 10]
element from 2D :  7
dimension:  2


In [10]:
import numpy as np
x=np.array([[[0,1,2,3,4],[5,6,7,8,10]],[[10,11,12,13,14],[15,16,17,18,10]]])
print("3D : ",x)
print("1D from 3D : ",x[1])
print("element from 3D : ",x[1][1][3])
print("dimension: ",x.ndim)

3D :  [[[ 0  1  2  3  4]
  [ 5  6  7  8 10]]

 [[10 11 12 13 14]
  [15 16 17 18 10]]]
1D from 3D :  [[10 11 12 13 14]
 [15 16 17 18 10]]
element from 3D :  18
dimension:  3


# revive zone alert

<class 'numpy.ndarray'>
0
