In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3 4 5]
[100   2   3   4   5]


In [9]:
# here b is imaginary temp array which only show not take extra space like in copy()
import numpy as np
a=np.array([1,2,3,4,5,6])
b=a.view()
b[0]=100
print(a)
print(b)

[100   2   3   4   5   6]
[100   2   3   4   5   6]


# revision

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
b=a.copy()
a[0]=100
print(a)
print(b)

[100   2   3   4   5]
[1 2 3 4 5]


In [6]:
import numpy as np
x=np.array([1,2,3,4,5])
y=x.view()
x[0]=100
print(x)
print(y)

[100   2   3   4   5]
[100   2   3   4   5]


# shape array

In [13]:
import numpy as np
a=np.array([[1,2,3,4,5,6],[8,9,9,9,8,10]])
print(a)
print('row: ',a.shape[0])
print('col: ',a.shape[1])

[[ 1  2  3  4  5  6]
 [ 8  9  9  9  8 10]]
row:  2
col:  6


# reshape array

In [14]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,4) # break kro a array ko into 2 with each elem 4
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(2,3,2) # break kro a array ko into 2 fir uske dono part ko 3-3 m divide kro with each elem 2
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [18]:
import numpy as np
a=np.array([[1,2,3,4],[15,16,17,18]])
for i in np.nditer(a):  # for 2d,3d,4d.. print krne k liye multiple loop lgte hai whi  ye single function ki call pe sara data dedeta hai
    print(i) #nditer=nd+iter

1
2
3
4
15
16
17
18
