In [ ]:
"""concatenating methods in string 
1.) np.concatenate((a,b))
"""

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a=np.array([[1,2],[4,5]])
b=np.array([[6,7],[8,9]])
c=np.concatenate((a,b),axis=1)
print(c)


[[1 2 6 7]
 [4 5 8 9]]
