In [ ]:
# data types in python: string, integer, float, boolean, complex
# data type in numpy 
# i for integer
# b for boolean
# u for unsigned integer
# f for float
# c for complex float
# m for timedelta
# M for datetime
# O for object
# S for string
# U for unicode string
# V - memory

# checking the data type of numpy array -dtype

In [2]:
import numpy as np
a=np.array([1,2,3,5,6])
print(a.dtype)

int64


In [4]:
import numpy as np
a=np.array(['apple','banana','orange'])
print(a)
print(a.dtype)

['apple' 'banana' 'orange']
<U6


In [6]:
import numpy as np
a=np.array([1,2,3,4,5],dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [7]:
import numpy as np
a=np.array([1,2,3,4,5],dtype='O')
print(a)
print(a.dtype)

[1 2 3 4 5]
object


In [9]:
import numpy as np
a=np.array(['hunter','mango','shoot'],dtype='O')
print(a)
print(a.dtype)

['hunter' 'mango' 'shoot']
object


In [10]:
# i stand for integer 4 stand for 4byte
import numpy as np
a=np.array([1,2,3,4,5], dtype='i4')
print(a)
print(a.dtype)

[1 2 3 4 5]
int32


In [13]:
# convert data type in existing array
import numpy as np
a=np.array([1,2,3,4,5])
b=a.astype('S')
print(b)

[b'1' b'2' b'3' b'4' b'5']


In [17]:
import numpy as np
a=np.array([-1.4,2.5,3.9,4.1,5.0])
b=a.astype('i')
c=a.astype(bool)
print(b)
print(c)

[-1  2  3  4  5]
[ True  True  True  True  True]
