In [ ]:
# they do almost same task but suffle change oringinal array while permution not

# random.shuffle()

In [5]:
import numpy as np
from numpy import random
arr=np.array([1,2,3,4,5])
random.shuffle(arr)
print(arr)


[3 5 4 1 2]


# random.permutation()

In [7]:
import numpy as np
from numpy import random
arr=np.array([1,2,3,4,5])
random.permutation(arr)
print(arr)


[1 2 3 4 5]


In [16]:
import numpy as np
from numpy import random
arr=np.array([1,2,3,4,5])
print(random.permutation(arr))


[2 4 5 1 3]
