# np.where()

In [ ]:
# Purpose: Returns indices where a condition is True. It can also be used as a vectorized if-else

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
idx=np.where(arr==4)
print("print idx: ",idx)
print("value at index: ",arr[idx])

print idx:  (array([3]),)
value at index:  [4]


In [7]:
import numpy as np
arr=np.array([1,2,3,5,6,7,8])
idx=np.where(arr>=4)
print("where the val greater and equal to 4",idx)
print(arr[idx])

(array([3, 4, 5, 6]),)
[5 6 7 8]


In [11]:
import numpy as np
arr=np.array([1,2,3,5,6,7,8])
idxs=np.where(arr%2==0)
print(idxs)
idxs=np.where(arr%2==0,'even', 'odd') #it is like an comparator in c++ iftrue return these else that
print(idxs)

(array([1, 4, 6]),)
['odd' 'even' 'odd' 'odd' 'even' 'odd' 'even']


# ✅ np.searchsorted()

In [ ]:
"""✅ np.searchsorted()
Purpose: Finds indices where elements should be inserted to maintain order in a sorted array.

🔹 Syntax

np.searchsorted(sorted_array, values, side='left' or 'right')
side='left': returns the first suitable location

side='right': returns the last suitable location"""

In [17]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
idx=np.searchsorted(arr,5,side='left')
print(idx)
idx=np.searchsorted(arr,5,side='right')
print(idx)
idx=np.searchsorted(arr,[.5,7])
print(idx)

4
5
[0 6]
