# these is what you already learned in class 11th maths ch1 sets

In [ ]:
# 1.) unique for unique elements

In [3]:
import numpy as np
a=np.array([1,1,2,3,4,4,5,6,6,7])
print(np.unique(a))


[1 2 3 4 5 6 7]


In [5]:
# 2.)union1d of two set
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])
print(np.union1d(a,b))

[1 2 3 4 5 6 7 8]


In [6]:
# 3.)intersect1d of two set
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])
print(np.intersect1d(a,b))

[4 5]


In [7]:
# 4.) np.setdiff1d() – Difference Elements in a not in b:
print(np.setdiff1d(a,b))

[1 2 3]


In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print("Union:",        np.union1d(a, b))
print("Intersection:", np.intersect1d(a, b))
print("A - B:",        np.setdiff1d(a, b))
print("B - A:",        np.setdiff1d(b, a))
print("Symmetric:",    np.setxor1d(a, b))

Union: [1 2 3 4 5 6]
Intersection: [3 4]
A - B: [1 2]
B - A: [5 6]
Symmetric: [1 2 5 6]
