In [5]:
import numpy as np
x=np.array([0,1,2,3,4,5,6,7,8])
print(x)
print("print element from 5 to 7: ",x[5:8])
print("print element from 0 to 8: ",x[:8])
print("print element from 5 to 8: ",x[5:])

[0 1 2 3 4 5 6 7 8]
print element from 5 to 7:  [5 6 7]
print element from 0 to 8:  [0 1 2 3 4 5 6 7]
print element from 5 to 8:  [5 6 7 8]


In [13]:
import numpy as np
x=np.array([0,1,2,3,4,5,6,7,8])
print("print element on index diffrence 2: ",x[1:7:2])
print("print element of array on diffrence 2: ",x[::2])
print("print element of array on diffrence 3: ",x[::3])

print element on index diffrence 2:  [1 3 5]
print element of array on diffrence 2:  [0 2 4 6 8]
print element of array on diffrence 3:  [0 3 6]


In [16]:
import numpy as np
x=np.array([0,1,2,3,4,5,6,7,8])
print("Even element: ",x[::2])
print("Odd elemnts: ",x[1::2])

Even element:  [0 2 4 6 8]
Odd elemnts:  [1 3 5 7]


In [19]:
import numpy as np
x1=np.array([[0,1,2,3,4],[0,11,12,13,14]])
print(x1[1,1:4])

[11 12 13]


In [21]:
import numpy as np
sharad = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("same result: ",sharad[0][2])
print("same result: ",sharad[1][2])
print(sharad[0:2, 2])

same result:  3
same result:  8
[3 8]


In [29]:
import numpy as np
sharad = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]])
print("res1: ",sharad[0, 2:4])
print("res2: ",sharad[1, 2:4])
print("res3: ",sharad[2, 2:4])
print("res1+ res2+ res3: ",sharad[0:3, 2:4])

res1:  [3 4]
res2:  [8 9]
res3:  [13 14]
res1+ res2+ res3: /n [[ 3  4]
 [ 8  9]
 [13 14]]


In [4]:
import numpy as np
a=np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]])
print(a[1,3])
print(a[1:4,2])
# row1,col2
# row2,col2
# row3,col2

40
[ 30 300]


In [5]:
import numpy as np
a=np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]])
print(a[1,3])
print(a[0:4,0:4])
# row1,col0, col1, col2, col4
# row2,col2
# row3,col2

40
[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]]


In [ ]:
# array[start:stop:step]
# start: index to start from (inclusive)

# stop: index to stop at (exclusive)

# step: stride between elements