# sorting in array

In [ ]:
# ✅ 1. np.sort(): Returns a sorted copy of the array

In [3]:
import numpy as np
arr=np.array([8,5,7,6,4,1,2])
arrCopy=np.sort(arr)
print(arrCopy)

[1 2 4 5 6 7 8]


In [8]:
import numpy as np
arr2d = np.array([[4, 1], [3, 2]])
arrCopy=np.sort(arr2d, axis=1)  # horizontally sort
print(arrCopy)
arrCopy=np.sort(arr2d,axis=0)   # vertically sort
print(arrCopy)

[[1 4]
 [2 3]]
[[3 1]
 [4 2]]


In [ ]:
# ✅ 3. np.argsort(): Returns the indices that would sort the array

In [13]:
import numpy as np
arr=np.array([10,40,30])

idxs=np.argsort(arr)
print(idxs)



[0 2 1]


In [ ]:
# 4. np.lexsort((arr1,arr2)): Sort by multiple keys

In [15]:
import numpy as np
age=np.array([10,40,30])
names=np.array(['luke','marie','bob'])
idxs=np.lexsort((age,names))
print(idxs)
print(names[idxs])

[2 0 1]
['bob' 'luke' 'marie']


In [13]:
import pandas as pd
import numpy as np
rd=pd.read_csv(r"C:\Users\hp\Data Science ML\Pandas\udated_marksheet.csv")

tm=np.array(rd['Total_marks'])
idxs=np.lexsort((tm,np.array(rd['Name'])))
rd.iloc[idxs]


Unnamed: 0     Name  Internal_Marks  Theory_Marks  Total_marks  \
0            0    Alice               8            93          101   
1            1      Bob               9            49           58   
2            2  Charlie               8            40           48   
3            3    David              10            41           51   
4            4      Eva               8            49           57   
5            5    Frank              10            73           83   
6            6    Grace               8            99          107   
7            7   Hannah              10            98          108   
8            8    Isaac              10            77           87   
9            9     Jack               9            64           73   
10          10     Kara               9            62           71   
11          11     Liam              10            93          103   
12          12      Mia               9            74           83   
13          13   Nathan               9            43           52   
14          14   Olivia               8           100          108   
15          15     Paul              10            79           89   
16          16    Quinn               9            56           65   
17          17   Rachel               8            75           83   
18          18      Sam               8            70           78   
19          19     Tina               8            58           66   
20          20      Uma               9            79           88   
21          21   Victor              10            46           56   
22          22    Wendy               8            72           80   
23          23   Xander              10            99          109   
24          24     Yara               9            46           55   

    Percentage  isPass  
0    67.333333    True  
1    38.666667    True  
2    32.000000    True  
3    34.000000    True  
4    38.000000    True  
5    55.333333    True  
6    71.333333    True  
7    72.000000    True  
8    58.000000    True  
9    48.666667    True  
10   47.333333    True  
11   68.666667    True  
12   55.333333    True  
13   34.666667    True  
14   72.000000    True  
15   59.333333    True  
16   43.333333    True  
17   55.333333    True  
18   52.000000    True  
19   44.000000    True  
20   58.666667    True  
21   37.333333    True  
22   53.333333    True  
23   72.666667    True  
24   36.666667    True

In [15]:
import pandas as pd
import numpy as np

# Step 1: Read the CSV file
df = pd.read_csv(r"C:\Users\hp\Data Science ML\Pandas\udated_marksheet.csv")  # replace with your actual filename

# Step 2: Convert the 'total_marks' column to a NumPy array
marks = df['total_marks'].to_numpy()

# Step 3: Use lexsort to get sorted indices (ascending order)
# Note: lexsort sorts using the LAST key as the primary sort key
sorted_indices = np.lexsort((df['name'].to_numpy(), marks))

# Step 4: Reorder the DataFrame using sorted indices
sorted_df = df.iloc[sorted_indices]

# Step 5: Print or save the result
print(sorted_df)
# sorted_df.to_csv('sorted_output.csv', index=False)


KeyError: 'total_marks'

In [14]:
rd

Unnamed: 0     Name  Internal_Marks  Theory_Marks  Total_marks  \
0            0    Alice               8            93          101   
1            1      Bob               9            49           58   
2            2  Charlie               8            40           48   
3            3    David              10            41           51   
4            4      Eva               8            49           57   
5            5    Frank              10            73           83   
6            6    Grace               8            99          107   
7            7   Hannah              10            98          108   
8            8    Isaac              10            77           87   
9            9     Jack               9            64           73   
10          10     Kara               9            62           71   
11          11     Liam              10            93          103   
12          12      Mia               9            74           83   
13          13   Nathan               9            43           52   
14          14   Olivia               8           100          108   
15          15     Paul              10            79           89   
16          16    Quinn               9            56           65   
17          17   Rachel               8            75           83   
18          18      Sam               8            70           78   
19          19     Tina               8            58           66   
20          20      Uma               9            79           88   
21          21   Victor              10            46           56   
22          22    Wendy               8            72           80   
23          23   Xander              10            99          109   
24          24     Yara               9            46           55   

    Percentage  isPass  
0    67.333333    True  
1    38.666667    True  
2    32.000000    True  
3    34.000000    True  
4    38.000000    True  
5    55.333333    True  
6    71.333333    True  
7    72.000000    True  
8    58.000000    True  
9    48.666667    True  
10   47.333333    True  
11   68.666667    True  
12   55.333333    True  
13   34.666667    True  
14   72.000000    True  
15   59.333333    True  
16   43.333333    True  
17   55.333333    True  
18   52.000000    True  
19   44.000000    True  
20   58.666667    True  
21   37.333333    True  
22   53.333333    True  
23   72.666667    True  
24   36.666667    True