# 1.) normal trigno metric function

In [4]:
import numpy as np
radians=np.array([0,np.pi/2, np.pi])
print(np.sin(radians))
print(np.cos(radians))
print(np.tan(radians))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


# 2.) inverse of trignometry function (arc)

In [6]:
import numpy as np
vals=np.array([0,1,-1])
print(np.arcsin(vals))
print(np.arccos(vals))
print(np.arctan(vals))

[ 0.          1.57079633 -1.57079633]
[1.57079633 0.         3.14159265]
[ 0.          0.78539816 -0.78539816]


# 3.) degree <--> radian

In [11]:
import numpy as np
radians=np.array([0,np.pi/2, np.pi])
degree=np.rad2deg(radians)
print(degree)
rad=np.deg2rad(degree)
print(rad)

[  0.  90. 180.]
[0.         1.57079633 3.14159265]


# 4.) np.hypot hypotaneous

In [12]:
import numpy as np
print(np.hypot(3,4)) # b=3, h=4

5.0


# 5.) angle calculations np.arctan2(x,y)

In [17]:
rad=np.arctan2(1,1)
print(rad)
print("degree: ",np.rad2deg(rad))

0.7853981633974483
degree:  45.0


# 6.) hyperbolic function as like above u use np.cosh(), np.sinh(). np.tanh()